FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Agenda

Agenda is a simple API allowing consumers to schedule meeting on-line.

# Group User

Resource operations related to users in the API.


## Login [GET /user/login{?username,password}]

+ Parameter
    - username : `zhang3` (string, required) - User Name
    - password : `123` (required) - Password
    
+ Response 200
    
            {
                "success"
            }

## Register [POST /user/register{?username,password,email,phone}]

+ Parameter
    - username : `zhang3` (string, required) - User Name
    - password : `123` (required) - Password
    - email : `123@mail.com` (required)
    - phone : `12345678901` (required)

+ Request (application/json)

        {
            "username":"zhang3",
            "password":"zhang",
            "email":"zhang3@mail2.sysu.edu.cn",
            "phone":"1234567890"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 1,
                "username":"zhang3",
                "password":"zhang",
                "email":"zhang3@mail2.sysu.edu.cn",
                "phone":"1234567890"
            }


## List all Users [GET /users/allusers]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "username":"zhang3",
                "password":"zhang",
                "email":"zhang3@mail2.sysu.edu.cn",
                "phone":"12345678901"
            }, {
                "id":2,
                "username":"li4",
                "password":"li",
                "email":"li4@mail2.sysu.edu.cn",
                "phone":"12345678900"
            }
        ]
        
## Delete Current User [DELETE /users/deleteuser{?password}]

+ Parameters
    - password : `pass` (string, required)

+ Response 200
    
            {
                "success"
            }

# Group Meetings

Resources related to meetings in the API.

## Create a meeting [POST /meetings/newmeeting{?title,currentUser,participators,start,end}]

+ Parameters
    - title : `title` (string, required)
    - currentUser: `user` (string, required)
    - participators : `user2` (string, required)
    - start : `2017-11-01T10:00` (string, required)
    - end : `2017-11-01T11:00` (string, required)

+ Request (application/json)

        {
            "title":"title",
            "participators":"user"
            "participators":["user2"],
            "start":"2017-11-01T10:00",
            "end":"2017-11-01T11:00"
        }

+ Response 201 (application/json)

    + Body

            {
                "id":1,
                "title":"Meeting",
                "sponsor":"user1",
                "participators":["user2"],
                "start":"2017-11-01 10:00",
                "end":"2017-11-01 11:30"
            }

## list all meeting [GET /meetings/allmeetings]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "title":"Meeting1",
                "sponsor":"user1",
                "participators":["user2"],
                "start":"2017-11-01 10:00",
                "end":"2017-11-01 11:30"
            }, {
                "id":2,
                "title":"Meeting2",
                "sponsor":"user1",
                "participators":["user3"],
                "start":"2017-11-02 10:00",
                "end":"2017-11-02 11:30"
            }

## clear all meetings [DELETE /meetings/deletemeetings]

+ Response 200
    
            {
                "success"
            }